version: "3.8"
services:
  api:
    build: .
    container_name: faceid_api
    env_file: .env
    environment:
      DB_HOST: db
      DB_PORT: 5432
    depends_on:
      - db
    ports: ["${API_PORT}:8000"]
    volumes:
      - ./:/app
    command: >
      bash -lc "gunicorn app.main:app -k uvicorn.workers.UvicornWorker
      -w ${WEB_CONCURRENCY:-4} -b 0.0.0.0:8000 --timeout 60"

  db:
    image: ankane/pgvector:latest
    container_name: faceid_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./migrations.sql:/docker-entrypoint-initdb.d/000_migrations.sql:ro
    command: ["postgres", "-c", "shared_buffers=256MB", "-c", "max_connections=200"]

volumes:
  pgdata: